CREATE TABLE IF NOT EXISTS bioclim_geom(
	index char(10),
	lat double precision,
	lon double precision,
	year integer,
	bio1 double precision,
	bio2 double precision,
	bio3 double precision,
	bio4 double precision,
	bio5 double precision,
	bio6 double precision,
	bio7 double precision,
	bio8 double precision,
	bio9 double precision,
	bio10 double precision,
	bio11 double precision,
	bio12 double precision,
	bio13 double precision,
	bio14 double precision,
	bio15 double precision,
	bio16 double precision,
	bio17 double precision,
	bio18 double precision,
	bio19 double precision,
	location geometry
)

